### PR TITLE
Removed unnecessary dependencies.

### PR DESCRIPTION
**Pull request by adam-drewery**
...also removed some visual studio detritus and removed unused using statements.

I wanted to use this project but was put off by the dependencies it pulls in. This pull request removes those dependencies:

- I Replaced log4net calls with `Console.WriteLine()`. I could replace these with events though if you'd prefer to be able to hook up your own logging framework still.
- Stanford Midi stuff is in its own project: `MarkovSharp.Midi`
- `Newtonsoft.Json` has been replaced with the built-in `JavaScriptSerializer` in the couple of places where it was used.

### CODE REVIEW

**Comment by ThibaultLemaire** [comment]
+1 for removing unnecessary files and moving the midi strategy to its own project. I believe it's too specific to justify a dependency on the nuget package.

As for the logging, I'm not a big fan of having console writes, so yeah I would personaly rather go for delegates or events.

For the serialization, Newtonsoft is pretty standard and shouldn't be too much of a problem as a dependency, but maybe we could question the very fact that we need JSON serialization?

**Comment by ThibaultLemaire** [comment]
Also, This PR feels to me like it's too big, maybe splitting it into smaller parts would increase the chances of individual parts being accepted, and would help discuss specific topics?

**Comment by adam-drewery** [comment]
hey @ThibaultLemaire, some fair points there- need some input from @chriscore before I can go ahead with anything here though unfortunately! Alternatively, if we don't get any answers I'm quite happy to start a new project based on my fork of this one, I've already got another pull request converting the project to .net standard 1.0 which will suit your needs with any .net core version.

**Comment by ThibaultLemaire** [comment]
Let's give him 2 weeks

**Pull request closed without merging**
